name: linter checks
on:
  push:

jobs:
  linter:
    name: "Linter Checks"
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Check markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          ignore: ./LICENSE.md
